### ISSUE TITLE
The loop parameter to Queue is deprecated/removed

### ISSUE THREAD

**Issue by cedricbonhomme** [javipalanca/spade#103]
* SPADE version: 3.2.2
* Python version: 3.10 and 3.11
* Operating System: 22.10 (Kinetic Kudu)

### Description

The loop parameter to Queue is deprecated/removed

```bash
$ python pumpkin/correlation.py 
Agent starting . . .
Traceback (most recent call last):
  File "/home/cedric/git/pumpkin/pumpkin/correlation.py", line 27, in <module>
    future.result()
  File "/home/cedric/.pyenv/versions/3.11.0/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/cedric/.pyenv/versions/3.11.0/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/cedric/.local/share/hatch/env/virtual/pumpkin/bXdZuwLV/pumpkin/lib/python3.11/site-packages/spade/agent.py", line 137, in _async_start
    await self.setup()
  File "/home/cedric/git/pumpkin/pumpkin/correlation.py", line 21, in setup
    self.add_behaviour(b)
  File "/home/cedric/.local/share/hatch/env/virtual/pumpkin/bXdZuwLV/pumpkin/lib/python3.11/site-packages/spade/agent.py", line 251, in add_behaviour
    behaviour.set_agent(agent=self)
  File "/home/cedric/.local/share/hatch/env/virtual/pumpkin/bXdZuwLV/pumpkin/lib/python3.11/site-packages/spade/behaviour.py", line 63, in set_agent
    self.queue = asyncio.Queue(loop=self.agent.loop)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Queue.__init__() got an unexpected keyword argument 'loop'
```

Simply removing the use of the argument `loop` in spade/behaviour.py (line 63) fixed the issue.

Tested with Python 3.10 and 3.11. From the documentation [here](https://docs.python.org/3/library/asyncio-eventloop.html):

> Application developers should typically use the high-level asyncio functions, such as [asyncio.run()](https://docs.python.org/3/library/asyncio-runner.html#asyncio.run), and should rarely need to reference the loop object or call its methods. This section is intended mostly for authors of lower-level code, libraries, and frameworks, who need finer control over the event loop behavior.

It is no more needed to pass the global event loop.

Do you plan to fix this `soonish`` ? Else I must try with Python 3.8. or 3.9.

Thank you.

**Comment by cedricbonhomme** [comment]
I just noticed that the PR #102 is solving this issue, for your information.

**Comment by gciatto** [comment]
Any ETA on this?

**Comment by 0x1F602** [comment]
@cedricbonhomme @gciatto I've successfully used python 3.9 on the develop branch of this repo. @javipalanca updated the docs on the develop branch and I can confirm it works for me.
