### ISSUE TITLE
Error When executing runspade.py

### ISSUE THREAD

**Issue by erandac** [javipalanca/spade#11]
I'm getting following error on both Ubuntu 12.04 and Mac. 

SPADE  2.2  gusarba@gmail.com - http://spade2.googlecode.com
Starting SPADE....
Traceback (most recent call last):
  File "runspade.py", line 141, in main
    platform.start()
  File "/home/erandac/Development/spade/spade/spade_backend.py", line 47, in start
    self.acc = self.runAgent(self.config, "acc", Platform.SpadePlatform)
  File "/home/erandac/Development/spade/spade/spade_backend.py", line 28, in runAgent
    agent = agentClass(jid, passwd, server, port, config=config)
  File "/home/erandac/Development/spade/spade/Platform.py", line 99, in **init**
    PlatformAgent.**init**(self, node, password, server, port, config=config, debug=[])
  File "/home/erandac/Development/spade/spade/Agent.py", line 1567, in **init**
    self._shutdown()
  File "/home/erandac/Development/spade/spade/Agent.py", line 1630, in _shutdown
    self.takeDown()
  File "/home/erandac/Development/spade/spade/Platform.py", line 123, in takeDown
    for k, _mtp in self.mtps.items():
AttributeError: 'SpadePlatform' object has no attribute 'mtps'
'SpadePlatform' object has no attribute 'mtps'
 [failed]

**Comment by AhmedMahran** [comment]
Hi,
Can you tell me exactly what should I write in the command window while running the configure.py file!
Thanks!

**Comment by mschatten** [comment]
Dear Ahmed,

you should use:

configure.py localhost

or

configure.py 127.0.0.1

If you are running SPADE on your local machine.

All the best,

M.

--
Markus Schatten, PhD
Assistant professor and head of Artificial Intelligence Lab
University of Zagreb
Faculty of Organization and Informatics
Pavlinska 2, 42000 Varazdin, Croatia
http://www.foi.hr/nastavnici/schatten.markus/index.html
http://www.researchgate.net/profile/Markus_Schatten1
http://ai.foi.hr

**Comment by AhmedMahran** [comment]
Thanks Markus, now it's working on my local computer..
Regards,
Ahmed
