### ISSUE TITLE
not working in python 3.7.4

### ISSUE THREAD

**Issue by vinigracindo** [javipalanca/spade#70]
* SPADE version: 3.1.3
* Python version: 3.7.4
* Operating System: Win10 64x

### Description

>>> from spade import agent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\easylab\agent\env\lib\site-packages\spade\__init__.py", line 3, in <module>
    from . import agent
  File "D:\workspace\easylab\agent\env\lib\site-packages\spade\agent.py", line 18, in <module>
    from spade.web import WebApp
  File "D:\workspace\easylab\agent\env\lib\site-packages\spade\web.py", line 6, in <module>
    from aiohttp import web as aioweb
  File "D:\workspace\easylab\agent\env\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "D:\workspace\easylab\agent\env\lib\site-packages\aiohttp\client.py", line 63, in <module>
    from .client_reqrep import ClientRequest as ClientRequest
  File "D:\workspace\easylab\agent\env\lib\site-packages\aiohttp\client_reqrep.py", line 29, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "D:\workspace\easylab\agent\env\lib\site-packages\aiohttp\multipart.py", line 703, in <module>
    class MultipartWriter(Payload):
  File "D:\workspace\easylab\agent\env\lib\site-packages\aiohttp\multipart.py", line 786, in MultipartWriter
    headers: Optional[MultiMapping[str]]=None
TypeError: 'ABCMeta' object is not subscriptable

**Comment by Balannen** [comment]
@vinigracindo try installing Python module `aiohttp`. That solved it for me a couple days ago. For example: `python3 -m pip install aiohttp`.

Although, the used system in my case was Ubuntu (with Python 3.6+).

**Comment by javipalanca** [comment]
Hi. I've just published a new version in PyPI (3.1.4) that I hope will fix this bug.
